import { readFlatFrontmatter } from "./frontmatter.js";
import type { WorkflowSummary } from "./registry.js";

/** Collapse a value to a single safe line for use in a YAML frontmatter scalar:
 *  newlines/CRs become spaces, runs of whitespace collapse, ends trimmed.
 *  This guarantees the value cannot break out of the frontmatter block
 *  (e.g. an embedded `\n---\n`) or span multiple lines. */
function sanitizeInline(value: string): string {
  return value.replace(/[\r\n]+/g, " ").replace(/\s+/g, " ").trim();
}

/** Escape Markdown table cell delimiters so a `|` in user text doesn't
 *  introduce spurious columns. Also collapses newlines (a cell is one line). */
function escapeCell(value: string): string {
  return sanitizeInline(value).replace(/\|/g, "\\|");
}

/** Read a generated skill's flat frontmatter as `key: value` string pairs.
 *  Thin alias over the shared {@link readFlatFrontmatter}; the generated-skill
 *  marker (`perspecta_generated`/`perspecta_version`) drives pruning, so this
 *  must stay CRLF-tolerant — which the shared parser guarantees. */
export const readSkillFrontmatter = readFlatFrontmatter;

/** Per-workflow SKILL.md — thin: identity + trigger + canvas path + pointer. */
export function renderWorkflowSkill(s: WorkflowSummary): string {
  return `---
name: ${s.name}
description: ${sanitizeInline(s.trigger)}
perspecta_generated: true
perspecta_source: ${s.canvasPath}
---
Use the \`perspecta-workflow\` skill for how to walk a workflow. This one:

1. Walk the canvas at \`${s.canvasPath}\` via MCP \`workflow_start(...)\`.
2. If the perspecta-workflow MCP tools aren't connected this session,
   read the canvas + node-notes and walk them manually.
`;
}

/** The generated registry note listing every workflow. */
export function renderRegistry(summaries: WorkflowSummary[]): string {
  const header = `---
generated_by: perspecta-workflow
---
# Workflows

`;
  if (summaries.length === 0) {
    return header + "_No workflows defined in this vault yet._\n";
  }
  const rows = summaries
    .map((s) => `| ${escapeCell(s.name)} | ${escapeCell(s.purpose)} | ${escapeCell(s.trigger)} | ${s.nodeCount} | \`${s.canvasPath}\` |`)
    .join("\n");
  return (
    header +
    "| Name | Purpose | When to use | Nodes | Canvas |\n" +
    "| --- | --- | --- | --- | --- |\n" +
    rows +
    "\n"
  );
}

/** The plugin-owned generic skill, version-stamped. */
export function renderGenericSkill(version: string): string {
  return `---
name: perspecta-workflow
description: Use when the user asks for a multi-step vault task that matches a defined Perspecta workflow, or asks to run/list workflows. Discovers and walks workflow canvases.
perspecta_version: ${version}
---
<!-- Generated by Perspecta Workflow v${version} — do not hand-edit; overwritten on plugin update. -->

# Perspecta workflows

This vault defines **Perspecta workflows**: Obsidian Canvas files walked as
directed flowcharts from a start node to an end node. Each workflow also has its
own generated skill (its \`description\` says when to use it) and is listed in
\`_agents/workflows/INDEX.md\`.

## Running a workflow

1. Resolve the workflow to its canvas path (from the per-workflow skill's
   \`perspecta_source\`, or from \`_agents/workflows/INDEX.md\`).
2. Prefer the MCP tools when the \`perspecta-workflow\` server is connected:
   - \`workflow_start(canvasPath)\` → a session id.
   - \`workflow_current(session)\` → the current node's instruction + outgoing edges.
   - \`workflow_advance(session, edge?, outputs?)\` → record outputs, follow an
     edge (a label is required at a branch/loop).
   - \`workflow_status(session)\` / \`workflow_context(session)\` to inspect progress.
3. If the MCP tools are not available, read the canvas JSON and each node-note
   directly and walk them: start at the \`start\` node, follow labeled edges, and
   stop at the \`end\` node.

## Listing workflows

Read \`_agents/workflows/INDEX.md\` and present the Name / Purpose / When-to-use
columns.
`;
}
