import type { PflowDocument, PflowNode } from "../pflow/schema.js";
import { topoOrder, inWires, nodeById } from "../pflow/topo.js";
import { validatePflow } from "../pflow/validate.js";
import { lintEmittedScript } from "./emit-lint.js";

/** JSON.stringify yields a spec-compliant double-quoted JS string literal with
 *  correct escaping of quotes, backslashes, and control chars. */
export function jsString(value: string): string {
  return JSON.stringify(value);
}

/** Render `export const meta = {...}` as a pure literal. Phases are the
 *  distinct, declaration-ordered `phase` annotations on nodes. */
export function renderMeta(doc: PflowDocument): string {
  const phases: string[] = [];
  for (const n of doc.nodes) {
    if (n.phase && !phases.includes(n.phase)) phases.push(n.phase);
  }
  const phaseLines = phases.map((p) => `    { title: ${jsString(p)} },`).join("\n");
  return [
    "export const meta = {",
    `  name: ${jsString(doc.workflow.name)},`,
    `  description: ${jsString(doc.workflow.description)},`,
    "  phases: [",
    phaseLines,
    "  ],",
    "}",
  ].join("\n");
}

/** A safe JS identifier for a node's output variable. */
function varName(node: PflowNode): string {
  const base = (node.label || node.id).replace(/[^A-Za-z0-9_]/g, "_").replace(/^([0-9])/, "_$1");
  return `${base}_${node.id}`.replace(/[^A-Za-z0-9_]/g, "_");
}

/** The source variable feeding a node's single input (linear subset). */
function inputVar(doc: PflowDocument, node: PflowNode): string {
  const wires = inWires(doc, node.id);
  if (wires.length === 0) return "args";
  const src = nodeById(doc, wires[0].from.nodeId)!;
  return src.kind === "input" ? "args" : varName(src);
}

function emitNode(doc: PflowDocument, node: PflowNode): string {
  switch (node.kind) {
    case "input":
      return "";
    case "agent": {
      const v = varName(node);
      const prompt = jsString(node.prompt ?? node.label);
      const label = jsString(node.label);
      return `  const ${v} = await agent(${prompt}, { label: ${label} });`;
    }
    case "output": {
      const v = inputVar(doc, node);
      return `  return ${v};`;
    }
    case "split":
    case "join":
    case "loop":
    case "verify":
    case "synthesize":
    case "branch":
      throw new Error(`scriptgen M1: node kind "${node.kind}" (node ${node.id}) is not yet supported by the Claude Code emitter`);
    case "script":
      return `  // script node ${node.id}\n${(node.config?.body as string) ?? ""}`;
  }
}

/** Compile a .pflow document to a native Claude Code dynamic-workflow script.
 *  Deterministic: same document -> byte-identical output. Throws if the
 *  document fails validation or the emitted code fails emit-lint. */
export function generateClaudeCodeWorkflow(doc: PflowDocument): string {
  const validation = validatePflow(doc);
  if (!validation.ok) {
    const msg = validation.errors.map((e) => `  - [${e.rule}] ${e.message}`).join("\n");
    throw new Error(`pflow validation failed:\n${msg}`);
  }
  const order = topoOrder(doc);
  const header = `// Generated by Perspecta Workflow from ${doc.workflow.name}.pflow — do not hand-edit.`;
  const body = order
    .map((id) => emitNode(doc, nodeById(doc, id)!))
    .filter((line) => line.length > 0)
    .join("\n");
  const code = [header, "", renderMeta(doc), "", body, ""].join("\n");

  const lint = lintEmittedScript(code);
  if (!lint.ok) {
    const msg = lint.violations.map((v) => `  - banned token "${v.token}" at index ${v.index}`).join("\n");
    throw new Error(`emit-lint failed (non-deterministic or sandbox-illegal output):\n${msg}`);
  }
  return code;
}
