import type { PflowDocument, PflowNode } from "../pflow/schema.js";
import { topoOrder, inWires, nodeById } from "../pflow/topo.js";
import { validatePflow } from "../pflow/validate.js";
import { lintEmittedScript } from "./emit-lint.js";

/** JSON.stringify yields a spec-compliant double-quoted JS string literal with
 *  correct escaping of quotes, backslashes, and control chars. */
export function jsString(value: string): string {
  return JSON.stringify(value);
}

/** Escape a string for safe inclusion as the LITERAL portion of a template
 *  literal (backticks). Backslashes, backticks, and `${` sequences are escaped
 *  so user text can never break out or introduce an unintended interpolation. */
export function escapeTemplate(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

/** Render `export const meta = {...}` as a pure literal. Phases are the
 *  distinct, declaration-ordered `phase` annotations on nodes. */
export function renderMeta(doc: PflowDocument): string {
  const phases: string[] = [];
  for (const n of doc.nodes) {
    if (n.phase && !phases.includes(n.phase)) phases.push(n.phase);
  }
  const phaseLines = phases.map((p) => `    { title: ${jsString(p)} },`).join("\n");
  return [
    "export const meta = {",
    `  name: ${jsString(doc.workflow.name)},`,
    `  description: ${jsString(doc.workflow.description)},`,
    "  phases: [",
    phaseLines,
    "  ],",
    "}",
  ].join("\n");
}

/** A safe, collision-proof JS identifier for a node's output variable. The
 *  node's INDEX in `doc.nodes` (unique by construction) guarantees distinct
 *  identifiers even when two nodes' labels/ids sanitize to the same text. */
function varName(doc: PflowDocument, node: PflowNode): string {
  const base = (node.label || node.id).replace(/[^A-Za-z0-9_]/g, "_").replace(/^([0-9])/, "_$1");
  const index = doc.nodes.indexOf(node);
  return `${base}_${index}`.replace(/[^A-Za-z0-9_]/g, "_");
}

/** The source variable feeding a node's single input (linear subset). */
function inputVar(doc: PflowDocument, node: PflowNode): string {
  const wires = inWires(doc, node.id);
  if (wires.length === 0) return "args";
  const src = nodeById(doc, wires[0].from.nodeId)!;
  return src.kind === "input" ? "args" : varName(doc, src);
}

function emitNode(doc: PflowDocument, node: PflowNode): string {
  switch (node.kind) {
    case "input":
      return "";
    case "agent": {
      const v = varName(doc, node);
      const label = jsString(node.label);
      const base = node.prompt ?? node.label;
      // Thread upstream dataflow into the prompt as labelled context blocks.
      // Iterate `node.inputs` in DECLARED ORDER (not wire order) so the emitted
      // text is deterministic. For each input port that has an incoming wire,
      // interpolate the source variable (`args` for input-sourced ports).
      const incoming = inWires(doc, node.id);
      const blocks: string[] = [];
      for (const port of node.inputs) {
        const wire = incoming.find((w) => w.to.portId === port.id);
        if (!wire) continue;
        const src = nodeById(doc, wire.from.nodeId);
        if (!src) continue;
        const srcVar = src.kind === "input" ? "args" : varName(doc, src);
        blocks.push(`\n\n<context name="${port.name}">\n\${${srcVar}}\n</context>`);
      }
      if (blocks.length === 0) {
        // No woven dataflow — keep the static prompt a plain string literal.
        return `  const ${v} = await agent(${jsString(base)}, { label: ${label} });`;
      }
      // Build a template literal: base prompt followed by context blocks.
      const tmpl = "`" + escapeTemplate(base) + blocks.join("") + "`";
      return `  const ${v} = await agent(${tmpl}, { label: ${label} });`;
    }
    case "output": {
      const v = inputVar(doc, node);
      return `  return ${v};`;
    }
    case "split":
    case "join":
    case "loop":
    case "verify":
    case "synthesize":
    case "branch":
      throw new Error(`scriptgen M1: node kind "${node.kind}" (node ${node.id}) is not yet supported by the Claude Code emitter`);
    case "script":
      return `  // script node ${node.id}\n${(node.config?.body as string) ?? ""}`;
  }
}

/** Compile a .pflow document to a native Claude Code dynamic-workflow script.
 *  Deterministic: same document -> byte-identical output. Throws if the
 *  document fails validation or the emitted code fails emit-lint. */
export function generateClaudeCodeWorkflow(doc: PflowDocument): string {
  const validation = validatePflow(doc);
  if (!validation.ok) {
    const msg = validation.errors.map((e) => `  - [${e.rule}] ${e.message}`).join("\n");
    throw new Error(`pflow validation failed:\n${msg}`);
  }
  const order = topoOrder(doc);
  const header = `// Generated by Perspecta Workflow from ${doc.workflow.name}.pflow — do not hand-edit.`;
  const body = order
    .map((id) => emitNode(doc, nodeById(doc, id)!))
    .filter((line) => line.length > 0)
    .join("\n");
  const code = [header, "", renderMeta(doc), "", body, ""].join("\n");

  const lint = lintEmittedScript(code);
  if (!lint.ok) {
    const msg = lint.violations.map((v) => `  - banned token "${v.token}" at index ${v.index}`).join("\n");
    throw new Error(`emit-lint failed (non-deterministic or sandbox-illegal output):\n${msg}`);
  }
  return code;
}
